apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  serviceName: opensearch
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.19.2
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9600
          name: metrics
        env:
        - name: discovery.type
          value: single-node
        - name: plugins.security.disabled
          value: "true"
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          value: "BoxbgaWec5zXBcUML+fSxI3bA+sPV0Eh"
        resources:
          requests:
            memory: "1Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "4"
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
  volumeClaimTemplates:
  - metadata:
      name: opensearch-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard-rwo
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  ports:
  - port: 9200
    name: http
  - port: 9600
    name: metrics
  selector:
    app: opensearch
